{{- if .Values.routeParentRefs }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: "gitops-updater-httproute"
  namespace: '{{ .Release.Namespace }}'
spec:
  parentRefs:
    {{- range .Values.routeParentRefs }}
    - name: {{ .name }}
      namespace: {{ .namespace | default $.Release.Namespace }}
      {{- if .sectionName }}
      sectionName: {{ .sectionName }}
      {{- end }}
      {{- if .port }}
      port: {{ .port }}
      {{- end }}
    {{- end }}
  hostnames:
    - {{ .Values.hostname }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /gitops-updater
      backendRefs:
        - name: gitops-updater
          port: 80
  {{- end }}