apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: "gitops-updater-httproute"
  namespace: '{{ .Release.Namespace }}'
spec:
  parentRefs:
    - name: '{{ .Values.gatewayName }}'
      namespace: '{{ .Release.Namespace }}'
  hostnames:
    - {{ .Values.hostname }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /gitops-updater
      backendRefs:
        - name: gitops-updater
          port: 80